# .github/workflows/ci.yml

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
  
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  
  build:
    name: Build
    needs: [Lint, Test]
    uses: ./.github/workflows/build-docker.yml