# .github/workflows/ci.yml

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  test:
    uses: ./.github/workflows/test.yml
  
  build-docker:
    uses: ./.github/workflows/build-docker.yml